### ISSUE TITLE
dans les bois ou un labyrinthe ?

### ISSUE THREAD

**Issue by QuVil** [PolytechLyon/git-5a-g2-thomas-suard-sublet-villermet#11]
gary et dylan y'a conflit de où il s'est perdu entre vos parties

**Comment by Skyblu77** [comment]
CAD ?

**Comment by Skyblu77** [comment]
La labyrinthe c'était dans les dés

**Comment by QuVil** [comment]
@GaryOma a mis qu'il s'était perdu dans les bois
mettez vous d'accord vite fait

**Comment by tancou** [comment]
@GaryOma C'est dans un labyrinthe normalement

**Comment by QuVil** [comment]
je fix ça @GaryOma
