### ISSUE TITLE
L'image n'est pas sur la 4e

### ISSUE THREAD

**Issue by QuVil** [PolytechLyon/git-5a-g2-thomas-suard-sublet-villermet#14]

**Comment by GaryOma** [comment]
j'ai fait la couverture moi, c'est sur le maître

**Comment by Skyblu77** [comment]
Tu ne l'as pas ajoutée ?

**Comment by GaryOma** [comment]
si si

**Comment by Skyblu77** [comment]
Je ne la vois pas sur la 4e

**Comment by GaryOma** [comment]
nan c'est l'image de couverture

**Comment by GaryOma** [comment]
faut que ce soit la 4eme de couv ?

**Comment by Skyblu77** [comment]
Oui

**Comment by QuVil** [comment]
oskour

**Comment by GaryOma** [comment]
ok je fix

**Comment by Skyblu77** [comment]
Après tu peux mettre une couv sur le livre si tu veux. On part sur un best seller là

**Comment by GaryOma** [comment]
c bon fixed
