### ISSUE TITLE
le master est broken af

### ISSUE THREAD

**Issue by GaryOma** [PolytechLyon/git-5a-g2-thomas-suard-sublet-villermet#3]
@QuVil ta partie a pas l'air d'aller au bon endroit sur le maître

**Comment by QuVil** [comment]
my bad j'oubliais que tu passais après mon chapitre

**Comment by Skyblu77** [comment]
Gary cesse de te plaindre

**Comment by lcsdavid** [comment]
Je confirme y'a un soucis sur le maître comme baisé !

**Comment by GaryOma** [comment]
mdr merci @lcsdavid
