### ISSUE TITLE
Structure de l'histoire

### ISSUE THREAD

**Issue by GaryOma** [PolytechLyon/git-5a-g2-thomas-suard-sublet-villermet#6]
Faut qu'on convienne d'une structure de l'histoire finale haha, je crois qu'il faut juste qu'on ait qu'un seul bloc de texte @QuVil  et pas des blocks séparés comme ça
![image](https://user-images.githubusercontent.com/9405810/65121769-14737480-d9f0-11e9-9d34-02d0aadc0a0c.png)

**Comment by Skyblu77** [comment]
Partie ? c'est la mienne et celle de Gary qui s'est pas foulé

**Comment by QuVil** [comment]
Je séparais pour faciliter les merge no souci
